In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import pygame
import sys

pygame 2.6.1 (SDL 2.28.4, Python 3.12.6)
Hello from the pygame community. https://www.pygame.org/contribute.html

In [6]:
# Generate Clients
customers = 100
MAXLAT = 256
MAXLONG = 256

latitudes = np.random.randint(0, MAXLAT, customers)
longitudes = np.random.randint(0, MAXLONG, customers)

cs_df = pd.DataFrame({
    'Lat': latitudes,
    'Long': longitudes
})
cs_df.index.name = 'Customer'
cs_df

          Lat  Long
Customer
0         250    30
1         149    52
2          49   191
3          72    37
4         189   231
...       ...   ...
95        230   117
96        139   106
97         95   246
98        115    54
99        127   160

[100 rows x 2 columns]

In [18]:
# Genrate Medications
meds_df = pd.DataFrame({
    'Medicine': [],
    'Lifespan': []
})
max_meds = 10
lifespan_mean = 25
lifespan_std = 10

LIFESPAN_MIN = 5

medicine = hex_strings = ['{:04x}'.format(np.random.randint(0, 0xFFFF)) for _ in range(max_meds)]

lifespan = np.random.normal(lifespan_mean, lifespan_std, max_meds)
lifespan = np.round(np.maximum(lifespan, LIFESPAN_MIN))

meds_df['Medicine'] = medicine
meds_df['Lifespan'] = lifespan

meds_df

  Medicine  Lifespan
0     361e      26.0
1     14af      39.0
2     2d32      31.0
3     8b00      36.0
4     02b0      29.0
5     73be      14.0
6     3f37      36.0
7     ae0b      42.0
8     95be      31.0
9     86c0      20.0